weights:
  W_xREG: 0.05
  W_uREG: 0.01
  W_gripper_pose: 1000.0
  W_gripper_pose_term: 100.0
  W_limit: 1000.0

safety_threshold: 0.02
dt: 0.01
gripper_depth: 0.1034

mesh:
  path: "/home/arthur/Desktop/Projects/PAMI/object_following_ocp/ressources/video_data/d02/campbells2/102ae42bff9940fc8f0b12c8a53d2675"
  obj_file: "102ae42bff9940fc8f0b12c8a53d2675.obj"
  texture_file: "material_0.png"
  scale: 0.08
  color: [0.8, 0.8, 0.8]
  handle_rot : 45


