[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"

[project]
authors = [{ name = "anon", email = "arthur.haffemayer@gmail.com" }]
name = "object_following_ocp"
version = "0.1.0"
description = "Panda robot following an object using optimal control."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colmpc>=0.3.0",
    "matplotlib>=3.9.4",
    "meshcat>=0.3.2",
    "natsort>=8.4.0",
    "proxsuite!=0.7.2.post1",
    "robomeshcat >=1.1.4",
    "pandas >=2.0.0",
    "pycollada >=0.8",
]

[[tool.uv.index]]
explicit = true
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"

[tool.uv.sources]
torch = [ { index = "pytorch-cpu" } ]
torchvision = [ { index = "pytorch-cpu" } ]